import { NextRequest, NextResponse } from "next/server";
let upstashLimiter: Record<string, { limit: (id: string) => Promise<{ success: boolean }> }> | null = null; let useUpstash = false;
async function initUpstash() { if (upstashLimiter !== null) return; const url = process.env.UPSTASH_REDIS_REST_URL; const token = process.env.UPSTASH_REDIS_REST_TOKEN; if (url && token) { try { const { Ratelimit } = await import("@upstash/ratelimit"); const { Redis } = await import("@upstash/redis"); const redis = new Redis({ url, token }); const cv = process.env.NEXT_PUBLIC_CACHE_VERSION || '1'; upstashLimiter = { api: new Ratelimit({ redis, limiter: Ratelimit.slidingWindow(30, "1 m"), prefix: `kd:v${cv}:rl:api` }), auth: new Ratelimit({ redis, limiter: Ratelimit.slidingWindow(5, "1 m"), prefix: `kd:v${cv}:rl:auth` }), search: new Ratelimit({ redis, limiter: Ratelimit.slidingWindow(20, "1 m"), prefix: `kd:v${cv}:rl:search` }) }; useUpstash = true;  } catch (e) { useUpstash = false; console.error('[rate-limit] Upstash init failed:', e); } } else { upstashLimiter = {}; console.warn('[rate-limit] Upstash env not set, using in-memory fallback'); } }
interface RateLimitEntry { count: number; resetAt: number; }
const memoryStore = new Map<string, RateLimitEntry>();
setInterval(() => { const now = Date.now(); for (const [k, v] of memoryStore) { if (v.resetAt < now) memoryStore.delete(k); } }, 300000);
function memoryRateLimit(id: string, max: number, windowMs: number) { const now = Date.now(); const entry = memoryStore.get(id); if (!entry || entry.resetAt < now) { memoryStore.set(id, { count: 1, resetAt: now + windowMs }); return { success: true, remaining: max - 1, reset: now + windowMs }; } entry.count++; return entry.count > max ? { success: false, remaining: 0, reset: entry.resetAt } : { success: true, remaining: max - entry.count, reset: entry.resetAt }; }
export type RateLimitTier = "api" | "auth" | "search";
const TIER: Record<RateLimitTier, { max: number; windowMs: number }> = { api: { max: 30, windowMs: 60000 }, auth: { max: 5, windowMs: 60000 }, search: { max: 20, windowMs: 60000 } };
export function getIp(req: NextRequest): string { return req.headers.get("x-forwarded-for")?.split(",")[0]?.trim() || req.headers.get("x-real-ip") || "unknown"; }
export const RATE_LIMITS = TIER;
export function rateLimitResponse() { return NextResponse.json({ error: "요청이 너무 많습니다." }, { status: 429 }); }
export async function rateLimit(req: NextRequest, tier: RateLimitTier = "api"): Promise<boolean> { await initUpstash(); const ip = getIp(req); const id = `${tier}:${ip}`; if (useUpstash && upstashLimiter) { try { const r = await upstashLimiter[tier].limit(id); return r.success; } catch { return true; } } const cfg = TIER[tier]; const r = memoryRateLimit(id, cfg.max, cfg.windowMs); return r.success; }
export async function checkRateLimit(req: NextRequest, tier: RateLimitTier = "api"): Promise<{ success: true } | { success: false; response: NextResponse }> { const ok = await rateLimit(req, tier); if (!ok) return { success: false, response: rateLimitResponse() }; return { success: true }; }
